export const USE_CASE_REGISTRY = {
  EMPLOYEE: {
    CREATE: Symbol.for('MODULE::APPLICATION::USE_CASE::EMPLOYEE::CREATE'),
    UPDATE: Symbol.for('MODULE::APPLICATION::USE_CASE::EMPLOYEE::UPDATE'),
    DELETE: Symbol.for('MODULE::APPLICATION::USE_CASE::EMPLOYEE::DELETE'),
    FIND: {
      ONE: Symbol.for('MODULE::APPLICATION::USE_CASE::EMPLOYEE::FIND::ONE'),
      ALL: Symbol.for('MODULE::APPLICATION::USE_CASE::EMPLOYEE::FIND::ALL'),
    },
  },
};
