import 'reflect-metadata';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ChakraUIProvider } from '../provider/ui/chakra/chakra.provider';
import TanStackQueryProvider from '../provider/query/tanstack.provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraUIProvider>
          <TanStackQueryProvider>{children}</TanStackQueryProvider>
        </ChakraUIProvider>
      </body>
    </html>
  );
}
